version: '3' # specify the version of the yml file - version 3
services:  # each service will be a container as specified below
    mongodb: # MongoDB as the first container 
        image: mongo
        ports:
        - *****:*****   
    get_tweets: # Second container to collect the tweets
        build: etl_job/get_tweets/ 
        volumes: 
        - ./etl_job/get_tweets/:/app 
        depends_on:
        - mongodb 
        env_file: # Keys for twitter API
        - credentials.env
    etl: # Sentiment analysis container
        build: etl_job/ 
        volumes: 
        - ./etl_job/:/app 
        depends_on:
        - mongodb
        - postgresdb
    postgresdb: #PostgresDB for saving the data after tweet sentiment analysis.
        image: postgres
        ports:
        - ****:****
        environment:
        - POSTGRES_USER=********
        - POSTGRES_PASSWORD=********
        - POSTGRES_DB=postgres
    metabase:
        image: metabase/metabase
        ports:
        - ****:****
        depends_on:
        - postgresdb
         
